//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 04:59:57 PM SGT 
//


package com.billing.app.noetic.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.billing.app.noetic.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.billing.app.noetic.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDownloaddocuments }
     * 
     */
    public GetDownloaddocuments createGetDownloaddocuments() {
        return new GetDownloaddocuments();
    }

    /**
     * Create an instance of {@link GetDownloaddocumentsResponse }
     * 
     */
    public GetDownloaddocumentsResponse createGetDownloaddocumentsResponse() {
        return new GetDownloaddocumentsResponse();
    }

    /**
     * Create an instance of {@link SReturnDownloadDocuments }
     * 
     */
    public SReturnDownloadDocuments createSReturnDownloadDocuments() {
        return new SReturnDownloadDocuments();
    }

    /**
     * Create an instance of {@link GetDownloadreceipt }
     * 
     */
    public GetDownloadreceipt createGetDownloadreceipt() {
        return new GetDownloadreceipt();
    }

    /**
     * Create an instance of {@link GetDownloadreceiptResponse }
     * 
     */
    public GetDownloadreceiptResponse createGetDownloadreceiptResponse() {
        return new GetDownloadreceiptResponse();
    }

    /**
     * Create an instance of {@link SReturnDownloadReceipt }
     * 
     */
    public SReturnDownloadReceipt createSReturnDownloadReceipt() {
        return new SReturnDownloadReceipt();
    }

    /**
     * Create an instance of {@link GetDownloadsoa }
     * 
     */
    public GetDownloadsoa createGetDownloadsoa() {
        return new GetDownloadsoa();
    }

    /**
     * Create an instance of {@link GetDownloadsoaResponse }
     * 
     */
    public GetDownloadsoaResponse createGetDownloadsoaResponse() {
        return new GetDownloadsoaResponse();
    }

    /**
     * Create an instance of {@link SReturnDownloadSoa }
     * 
     */
    public SReturnDownloadSoa createSReturnDownloadSoa() {
        return new SReturnDownloadSoa();
    }

    /**
     * Create an instance of {@link GetFacilityreceipts }
     * 
     */
    public GetFacilityreceipts createGetFacilityreceipts() {
        return new GetFacilityreceipts();
    }

    /**
     * Create an instance of {@link GetFacilityreceiptsResponse }
     * 
     */
    public GetFacilityreceiptsResponse createGetFacilityreceiptsResponse() {
        return new GetFacilityreceiptsResponse();
    }

    /**
     * Create an instance of {@link SReturnFacilityReceipts }
     * 
     */
    public SReturnFacilityReceipts createSReturnFacilityReceipts() {
        return new SReturnFacilityReceipts();
    }

    /**
     * Create an instance of {@link GetOutstandinginvoices }
     * 
     */
    public GetOutstandinginvoices createGetOutstandinginvoices() {
        return new GetOutstandinginvoices();
    }

    /**
     * Create an instance of {@link GetOutstandinginvoicesResponse }
     * 
     */
    public GetOutstandinginvoicesResponse createGetOutstandinginvoicesResponse() {
        return new GetOutstandinginvoicesResponse();
    }

    /**
     * Create an instance of {@link SReturnOutstandingInvoices }
     * 
     */
    public SReturnOutstandingInvoices createSReturnOutstandingInvoices() {
        return new SReturnOutstandingInvoices();
    }

    /**
     * Create an instance of {@link GetOverdueinvoices }
     * 
     */
    public GetOverdueinvoices createGetOverdueinvoices() {
        return new GetOverdueinvoices();
    }

    /**
     * Create an instance of {@link GetOverdueinvoicesResponse }
     * 
     */
    public GetOverdueinvoicesResponse createGetOverdueinvoicesResponse() {
        return new GetOverdueinvoicesResponse();
    }

    /**
     * Create an instance of {@link SReturnGetOverdueInvoices }
     * 
     */
    public SReturnGetOverdueInvoices createSReturnGetOverdueInvoices() {
        return new SReturnGetOverdueInvoices();
    }

    /**
     * Create an instance of {@link SendPayment }
     * 
     */
    public SendPayment createSendPayment() {
        return new SendPayment();
    }

    /**
     * Create an instance of {@link ArrayOfInt }
     * 
     */
    public ArrayOfInt createArrayOfInt() {
        return new ArrayOfInt();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ArrayOfDecimal }
     * 
     */
    public ArrayOfDecimal createArrayOfDecimal() {
        return new ArrayOfDecimal();
    }

    /**
     * Create an instance of {@link ArrayOfLong }
     * 
     */
    public ArrayOfLong createArrayOfLong() {
        return new ArrayOfLong();
    }

    /**
     * Create an instance of {@link SendPaymentResponse }
     * 
     */
    public SendPaymentResponse createSendPaymentResponse() {
        return new SendPaymentResponse();
    }

    /**
     * Create an instance of {@link SReturnSendPayment }
     * 
     */
    public SReturnSendPayment createSReturnSendPayment() {
        return new SReturnSendPayment();
    }

    /**
     * Create an instance of {@link GetTransactions }
     * 
     */
    public GetTransactions createGetTransactions() {
        return new GetTransactions();
    }

    /**
     * Create an instance of {@link GetTransactionsResponse }
     * 
     */
    public GetTransactionsResponse createGetTransactionsResponse() {
        return new GetTransactionsResponse();
    }

    /**
     * Create an instance of {@link SReturnGetTransactions }
     * 
     */
    public SReturnGetTransactions createSReturnGetTransactions() {
        return new SReturnGetTransactions();
    }

    /**
     * Create an instance of {@link SendFacilitypayment }
     * 
     */
    public SendFacilitypayment createSendFacilitypayment() {
        return new SendFacilitypayment();
    }

    /**
     * Create an instance of {@link SendFacilitypaymentResponse }
     * 
     */
    public SendFacilitypaymentResponse createSendFacilitypaymentResponse() {
        return new SendFacilitypaymentResponse();
    }

    /**
     * Create an instance of {@link SReturnFacilityPayment }
     * 
     */
    public SReturnFacilityPayment createSReturnFacilityPayment() {
        return new SReturnFacilityPayment();
    }

    /**
     * Create an instance of {@link ArrayOfDateTime }
     * 
     */
    public ArrayOfDateTime createArrayOfDateTime() {
        return new ArrayOfDateTime();
    }

}
