//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 04:59:57 PM SGT 
//


package com.billing.app.noetic.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="send_paymentResult" type="{http://tempurl.org}s_return_send_payment" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendPaymentResult"
})
@XmlRootElement(name = "send_paymentResponse")
public class SendPaymentResponse {

    @XmlElement(name = "send_paymentResult")
    protected SReturnSendPayment sendPaymentResult;

    /**
     * Gets the value of the sendPaymentResult property.
     * 
     * @return
     *     possible object is
     *     {@link SReturnSendPayment }
     *     
     */
    public SReturnSendPayment getSendPaymentResult() {
        return sendPaymentResult;
    }

    /**
     * Sets the value of the sendPaymentResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SReturnSendPayment }
     *     
     */
    public void setSendPaymentResult(SReturnSendPayment value) {
        this.sendPaymentResult = value;
    }

}
