//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 04:59:57 PM SGT 
//


package com.billing.app.noetic.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for s_return_facility_receipts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="s_return_facility_receipts"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="process_status" type="{http://tempurl.org}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="process_error" type="{http://tempurl.org}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="or_number" type="{http://tempurl.org}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="or_date" type="{http://tempurl.org}ArrayOfDateTime" minOccurs="0"/&gt;
 *         &lt;element name="reference_no" type="{http://tempurl.org}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="or_amount" type="{http://tempurl.org}ArrayOfDecimal" minOccurs="0"/&gt;
 *         &lt;element name="returnid" type="{http://tempurl.org}ArrayOfLong" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "s_return_facility_receipts", propOrder = {
    "processStatus",
    "processError",
    "orNumber",
    "orDate",
    "referenceNo",
    "orAmount",
    "returnid"
})
public class SReturnFacilityReceipts {

    @XmlElement(name = "process_status")
    protected ArrayOfString processStatus;
    @XmlElement(name = "process_error")
    protected ArrayOfString processError;
    @XmlElement(name = "or_number")
    protected ArrayOfString orNumber;
    @XmlElement(name = "or_date")
    protected ArrayOfDateTime orDate;
    @XmlElement(name = "reference_no")
    protected ArrayOfString referenceNo;
    @XmlElement(name = "or_amount")
    protected ArrayOfDecimal orAmount;
    protected ArrayOfLong returnid;

    /**
     * Gets the value of the processStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getProcessStatus() {
        return processStatus;
    }

    /**
     * Sets the value of the processStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setProcessStatus(ArrayOfString value) {
        this.processStatus = value;
    }

    /**
     * Gets the value of the processError property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getProcessError() {
        return processError;
    }

    /**
     * Sets the value of the processError property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setProcessError(ArrayOfString value) {
        this.processError = value;
    }

    /**
     * Gets the value of the orNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getOrNumber() {
        return orNumber;
    }

    /**
     * Sets the value of the orNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setOrNumber(ArrayOfString value) {
        this.orNumber = value;
    }

    /**
     * Gets the value of the orDate property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDateTime }
     *     
     */
    public ArrayOfDateTime getOrDate() {
        return orDate;
    }

    /**
     * Sets the value of the orDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDateTime }
     *     
     */
    public void setOrDate(ArrayOfDateTime value) {
        this.orDate = value;
    }

    /**
     * Gets the value of the referenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getReferenceNo() {
        return referenceNo;
    }

    /**
     * Sets the value of the referenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setReferenceNo(ArrayOfString value) {
        this.referenceNo = value;
    }

    /**
     * Gets the value of the orAmount property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfDecimal }
     *     
     */
    public ArrayOfDecimal getOrAmount() {
        return orAmount;
    }

    /**
     * Sets the value of the orAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfDecimal }
     *     
     */
    public void setOrAmount(ArrayOfDecimal value) {
        this.orAmount = value;
    }

    /**
     * Gets the value of the returnid property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLong }
     *     
     */
    public ArrayOfLong getReturnid() {
        return returnid;
    }

    /**
     * Sets the value of the returnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLong }
     *     
     */
    public void setReturnid(ArrayOfLong value) {
        this.returnid = value;
    }

}
